### ISSUE TITLE
The command /wildfire leads to java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by ghost** [IvyBits/Storm#2]
<b>CraftBukkit Build #</b> 1.3.2-R1.0
<b>Plugin Build # </b>Storm-dev-bkcmpt-V0.4
<b>Issue: </b>When the operator excutes the command /wildfire the fire appears for about 2 seconds then disppears. After that and error is displayed on the players chat then is disconnected `java.net.SocketException: Connection reset`. The server then locks up and players attemtping to connect will recieve the error `java.net.SocketException: Connection reset`.
<b>Log:</b>
`2012-09-29 20:16:00 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'wildfire' in plugin Storm v0.0.7B
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:498)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:282)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:577)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:473)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
    at com.github.StormTeam.Storm.CommandExecutors.wildfire(Unknown Source)
    at com.github.StormTeam.Storm.Commands.onCommand(Unknown Source)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 15 more`

**Comment by ghost** [comment]
Storm-dev-bkcmpt-346675 solved `java.net.SocketException: Connection reset` and the lockup. The wildfires are now working properly and the fire spreads like it should.
