### ISSUE TITLE
Meteors Throw Seemingly Random Exceptions On explode() 

### ISSUE THREAD

**Issue by Xyene** [IvyBits/Storm#5]
Exception stacktrace:

```
2012-10-04 12:50:04 [SEVERE] java.lang.NullPointerException
2012-10-04 12:50:04 [SEVERE]    at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.explode(Unknown Source)
2012-10-04 12:50:04 [SEVERE]    at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.move(Unknown Source)
2012-10-04 12:50:04 [SEVERE]    at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.F_(Unknown Source)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.World.entityJoinedWorld(World.java:1261)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:99)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.World.playerJoinedWorld(World.java:1243)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.World.tickEntities(World.java:1150)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:550)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:451)
2012-10-04 12:50:04 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
2012-10-04 12:50:04 [SEVERE] Unexpected exception
java.lang.NullPointerException
        at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.explode(Unknown Source)
        at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.move(Unknown Source)
        at com.github.StormTeam.Storm.Meteors.Entities.EntityMeteor.F_(Unknown Source)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1261)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:99)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1243)
        at net.minecraft.server.World.tickEntities(World.java:1150)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:550)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:451)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

```

**Comment by Xyene** [comment]
Fixed.
