### ISSUE TITLE
Storm bug 2012 - 1.3.2

### ISSUE THREAD

**Issue by DoJoMast3r** [IvyBits/Storm#6]
Big bug on the server told me to post it here!
Here you go!

9:28:28 AM [SEVERE]
=============Storm has encountered an error!=============
Stacktrace:
java.lang.NullPointerException
at com.github.StormTeam.Storm.StormUtil.broadcast(StormUtil.java:149)
at com.github.StormTeam.Storm.Blizzard.BlizzardWeather.start(BlizzardWeather.java:50)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeatherReal(WeatherManager.java:329)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeather(WeatherManager.java:271)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeather(WeatherManager.java:247)
at com.github.StormTeam.Storm.Weather.WeatherTrigger.run(WeatherTrigger.java:30)
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Storm version: 0.0.9B
Bukkit message: Bukkit did not catch this, so no additional info is available.
9:28:29 AM [World Portal v0.2.6, Orebfuscator v1.6.3, GroupManager v1.9 (2.8.4) (Phoenix), StreetLights v1.1.2.1, Buycraft v4.7, Vault v1.2.19-b248, RegenBlock vBeta 4.5, The Multiverse-Core Plugin, TreeAssist v4.4, DisguiseCraft v3.5, SurvivalGames vB 0.4.10, Announcer v1.3.1, Permissions v3.1.6, UltraLogger v1.6.1, BookShelf v1.2, OpenInv v1.8.7, Curseban v1.3.2.1, godPowers v2.7, CommandScheduler v0.0.3, MobArena v0.94.4.81, FoundDiamonds v3.6.1, CleanroomGenerator v1.0.0, Citizens v2.0, MultiInv v3.1.4, WorldEdit v5.4.2, Multiverse-NetherPortals v2.4-b530, MyCommand v3.4.1, WorldGuard v5.5.4, Jail v2.1.3, ChestRestock v2.3-b70, iConomy v7.0, CraftBukkitUpToDate v3.0.0, Weeping Angels v0.6, Lockette v1.7.4, FalseBookCore v0.93.1alpha, Essentials v2.9.4, MonsterHunt v1.5.1, ShowCaseStandalone v1.45, TARDIS v1.5.1, ServerSigns v2.5.2, Multiverse-Portals v2.4-b548, PlotMe v0.9, dynmap v0.80-1315, Denizen v0.7, Sentry v1.1.2, FalseBookIC v0.93.1alpha, EssentialsChat v2.9.4, FalseBookExtra v0.93.1alpha, WeatherMan v0.4.5, DeathTpPlus v3.9.16.2320, FalseBookCart v0.93.1alpha, EssentialsProtect v2.9.4, FalseBookChat v0.93.1alpha, FalseBookBlock v0.93.1alpha, EssentialsSpawn v2.9.4, Storm v0.0.9B, IslandWorld v1.2.8, EssentialsAntiBuild v2.9.4, AntiCheat v1.3.8-U4]
CraftBukkit version: 1.3.2-R2.0
Java version: 1.7.0_04
OS info: amd64 Windows 7, 6.1
Please report this error to the Storm ticket tracker (https://github.com/StormTeam/Storm/issues)!
===========================Storm===========================
9:28:29 AM [SEVERE]
=============Storm has encountered an error!=============
Stacktrace:
java.lang.NullPointerException
at com.github.StormTeam.Storm.StormUtil.broadcast(StormUtil.java:149)
at com.github.StormTeam.Storm.StormUtil.broadcast(StormUtil.java:161)
at com.github.StormTeam.Storm.Thunder_Storm.ThunderStormWeather.start(ThunderStormWeather.java:48)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeatherReal(WeatherManager.java:329)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeather(WeatherManager.java:271)
at com.github.StormTeam.Storm.Weather.WeatherManager.startWeather(WeatherManager.java:247)
at com.github.StormTeam.Storm.Weather.WeatherTrigger.run(WeatherTrigger.java:30)
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:53)
at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:510)
at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Storm version: 0.0.9B
Bukkit message: Bukkit did not catch this, so no additional info is available.
9:28:29 AM [World Portal v0.2.6, Orebfuscator v1.6.3, GroupManager v1.9 (2.8.4) (Phoenix), StreetLights v1.1.2.1, Buycraft v4.7, Vault v1.2.19-b248, RegenBlock vBeta 4.5, The Multiverse-Core Plugin, TreeAssist v4.4, DisguiseCraft v3.5, SurvivalGames vB 0.4.10, Announcer v1.3.1, Permissions v3.1.6, UltraLogger v1.6.1, BookShelf v1.2, OpenInv v1.8.7, Curseban v1.3.2.1, godPowers v2.7, CommandScheduler v0.0.3, MobArena v0.94.4.81, FoundDiamonds v3.6.1, CleanroomGenerator v1.0.0, Citizens v2.0, MultiInv v3.1.4, WorldEdit v5.4.2, Multiverse-NetherPortals v2.4-b530, MyCommand v3.4.1, WorldGuard v5.5.4, Jail v2.1.3, ChestRestock v2.3-b70, iConomy v7.0, CraftBukkitUpToDate v3.0.0, Weeping Angels v0.6, Lockette v1.7.4, FalseBookCore v0.93.1alpha, Essentials v2.9.4, MonsterHunt v1.5.1, ShowCaseStandalone v1.45, TARDIS v1.5.1, ServerSigns v2.5.2, Multiverse-Portals v2.4-b548, PlotMe v0.9, dynmap v0.80-1315, Denizen v0.7, Sentry v1.1.2, FalseBookIC v0.93.1alpha, EssentialsChat v2.9.4, FalseBookExtra v0.93.1alpha, WeatherMan v0.4.5, DeathTpPlus v3.9.16.2320, FalseBookCart v0.93.1alpha, EssentialsProtect v2.9.4, FalseBookChat v0.93.1alpha, FalseBookBlock v0.93.1alpha, EssentialsSpawn v2.9.4, Storm v0.0.9B, IslandWorld v1.2.8, EssentialsAntiBuild v2.9.4, AntiCheat v1.3.8-U4]
CraftBukkit version: 1.3.2-R2.0
Java version: 1.7.0_04
OS info: amd64 Windows 7, 6.1
Please report this error to the Storm ticket tracker (https://github.com/StormTeam/Storm/issues)!
This has been saved to the file ./Storm/errors/Storm_9f422e4b8ea2.error.log
===========================Storm===========================

**Comment by Xyene** [comment]
Did you happen to delete a world while Storm was still running?

**Comment by Xyene** [comment]
Should be fixed now.

**Comment by DoJoMast3r** [comment]
kk thanks!

Yeah i think i did on mv but its all fixed =)
