### ISSUE TITLE
Storm crash

### ISSUE THREAD

**Issue by pknull** [IvyBits/Storm#7]
=============Storm has encountered an error!=============
Stacktrace:
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.minecraft.server.Explosion.a(Explosion.java:203)
        at net.minecraft.server.World.createExplosion(World.java:1524)
        at net.minecraft.server.WorldServer.createExplosion(WorldServer.java:745)
        at org.bukkit.craftbukkit.CraftWorld.createExplosion(CraftWorld.java:441)
        at org.bukkit.craftbukkit.CraftWorld.createExplosion(CraftWorld.java:449)
        at com.timvisee.SafeCreeper.SafeCreeperEntityListener.createExplosionSound(SafeCreeperEntityListener.java:1232)
        at com.timvisee.SafeCreeper.SafeCreeperEntityListener.onEntityExplode(SafeCreeperEntityListener.java:662)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.minecraft.server.Explosion.a(Explosion.java:203)
        at net.minecraft.server.World.createExplosion(World.java:1524)
        at net.minecraft.server.WorldServer.createExplosion(WorldServer.java:745)
        at net.minecraft.server.EntityCreeper.h_(EntityCreeper.java:77)
        at uk.co.jacekk.bukkit.bloodmoon.entities.BloodMoonEntityCreeper.h_(BloodMoonEntityCreeper.java:108)
        at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
        at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
        at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
        at net.minecraft.server.World.tickEntities(World.java:1125)
        at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:547)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at com.github.StormTeam.Storm.Meteors.Listener.SafeExplosion.onExplode(SafeExplosion.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        ... 33 more

Storm version: 0.1.0B
Bukkit message: Could not pass event EntityExplodeEvent to Storm v0.1.0B
Plugins loaded: [CityWorld v2.03, WallClock v0.2.2, NickNamer v0.9, mcjobs v3.1.8, The Multiverse-Core Plugin, SafeCreeper v1.1.3, TreeAssist v4.4, dynmap v0.90-1347, SimpleVIPPerks v2.0, Chairs v1.5, PerformanceMonitor v1.6.6, EndReset v1.5, BooksWithoutBorders v1.2.1, MachinaCore v4.1.6, DisguiseCraft v3.5, MachinaFactory v4.1.6, SkylandsPlus v0.14.1, HoverPad v4.1.6, MachinaBuilder v4.1.6, MachinaPump v4.1.6, Enchanter v0.2, mcMMO v1.3.11-b1030, FoundDiamonds v3.6.1, CleanroomGenerator v1.0.0, Lift v27, MultiInv v3.1.4, Ptweaks v4.2, WorldEdit v5.4.3, ExtraFluffy v1.0.2, Stargate v0.7.8.1, PermissionsEx v1.19.3, WorldGuard v5.5.4, UberForest v1.1.0, MobileAdmin v3.2.5, BloodMoon v0.17, iConomy v7.0, LightDetector v1.3, LockTime v0.2, SecretSwitch v1.4, MoArrows v2.4.2, CraftBukkitUpToDate v3.0.0, Lockette v1.7.4, SimpleHat v1.2, S86 Powers v3.2.6, MachinaDrill v4.1.6, MachinaRedstoneBridge v4.1.6, StargateCommand v0.0.3, MachinaPlanter v4.1.6, MagicSpells v2.9, Storm v0.1.0B, MagicSpellsMemory v1.1, Vault v1.2.19-b248, Backpack vUnknown, ChestShop v3.46, WirelessRedstone v1.7b, DeathChest v1.11, pvparena v0.8.12.13, Herochat v5.6.1]
CraftBukkit version: 1.3.2-R2.0
Java version: 1.7.0_07
OS info: i386 Linux, 3.0.0-12-generic-pae
Please report this error to the Storm ticket tracker (https://github.com/StormTeam/Storm/issues)!
===========================Storm===========================

**Comment by Xyene** [comment]
I am guessing this was while using Tekkit?

**Comment by pknull** [comment]
It was not while using Tekkit. Vanilla client, mods as listed above on server.

**Comment by Xyene** [comment]
Interesting. Ah well. Bug should be fixed anyways now, in the latest bleeding build.

**Comment by pknull** [comment]
is there a link to the latest build? If there is I'd be happy to try it out again.

**Comment by Xyene** [comment]
http://www.stormteam.co.cc/projects/storm/wiki/Bleeding
